theme: jekyll-theme-midnight
show_downloads: true
github:
  zip_url: https://github.com/ravi-prakash1907/CaterApp/archive/refs/tags/v1.1-beta.zip
  site.github.tar_url: https://github.com/ravi-prakash1907/CaterApp/archive/refs/tags/v1.1-beta.tar.gz
